# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.scrollbar = QtWidgets.QScrollBar(self.centralwidget)
        self.scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.scrollbar.setObjectName("scrollbar")
        self.verticalLayout_3.addWidget(self.scrollbar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_label = QtWidgets.QLabel(self.centralwidget)
        self.left_label.setText("")
        self.left_label.setObjectName("left_label")
        self.horizontalLayout.addWidget(self.left_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.centre_label = QtWidgets.QLabel(self.centralwidget)
        self.centre_label.setText("")
        self.centre_label.setObjectName("centre_label")
        self.horizontalLayout.addWidget(self.centre_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.right_label = QtWidgets.QLabel(self.centralwidget)
        self.right_label.setText("")
        self.right_label.setObjectName("right_label")
        self.horizontalLayout.addWidget(self.right_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.open_video_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_video_button.setObjectName("open_video_button")
        self.verticalLayout_4.addWidget(self.open_video_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.autoLevel_button = QtWidgets.QRadioButton(self.groupBox)
        self.autoLevel_button.setChecked(True)
        self.autoLevel_button.setObjectName("autoLevel_button")
        self.verticalLayout_5.addWidget(self.autoLevel_button)
        self.reset_view_button = QtWidgets.QPushButton(self.groupBox)
        self.reset_view_button.setObjectName("reset_view_button")
        self.verticalLayout_5.addWidget(self.reset_view_button)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.roi_box = QtWidgets.QGroupBox(self.centralwidget)
        self.roi_box.setObjectName("roi_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.roi_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_roi_button = QtWidgets.QPushButton(self.roi_box)
        self.add_roi_button.setObjectName("add_roi_button")
        self.verticalLayout_2.addWidget(self.add_roi_button)
        self.clear_roi_button = QtWidgets.QPushButton(self.roi_box)
        self.clear_roi_button.setObjectName("clear_roi_button")
        self.verticalLayout_2.addWidget(self.clear_roi_button)
        self.verticalLayout_4.addWidget(self.roi_box)
        self.fluorescence_box = QtWidgets.QGroupBox(self.centralwidget)
        self.fluorescence_box.setObjectName("fluorescence_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fluorescence_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.measure_button = QtWidgets.QPushButton(self.fluorescence_box)
        self.measure_button.setObjectName("measure_button")
        self.verticalLayout.addWidget(self.measure_button)
        self.plot_button = QtWidgets.QPushButton(self.fluorescence_box)
        self.plot_button.setObjectName("plot_button")
        self.verticalLayout.addWidget(self.plot_button)
        self.save_button = QtWidgets.QPushButton(self.fluorescence_box)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.verticalLayout_4.addWidget(self.fluorescence_box)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button.setObjectName("quit_button")
        self.verticalLayout_4.addWidget(self.quit_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video ROI"))
        self.open_video_button.setText(_translate("MainWindow", "&Open"))
        self.open_video_button.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.groupBox.setTitle(_translate("MainWindow", "Display"))
        self.autoLevel_button.setText(_translate("MainWindow", "Auto level"))
        self.reset_view_button.setText(_translate("MainWindow", "Reset view"))
        self.roi_box.setTitle(_translate("MainWindow", "ROIs"))
        self.add_roi_button.setText(_translate("MainWindow", "Add"))
        self.clear_roi_button.setText(_translate("MainWindow", "Clear"))
        self.fluorescence_box.setTitle(_translate("MainWindow", "Fluorescence"))
        self.measure_button.setText(_translate("MainWindow", "Measure"))
        self.plot_button.setText(_translate("MainWindow", "Plot"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.quit_button.setText(_translate("MainWindow", "&Quit"))
        self.quit_button.setShortcut(_translate("MainWindow", "Ctrl+Q"))

from pyqtgraph import GraphicsLayoutWidget
